import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
}

const mockUrls = [
  "https://utfs.io/f/4033f3b2-0fc9-4a6e-95be-37009f50e078-7qajqq.png",
  "https://img.youtube.com/vi/uaCypXEJjes/maxresdefault.jpg",
  "https://img.youtube.com/vi/ODJkKJUnKtM/maxresdefault.jpg",
  "https://img.youtube.com/vi/G3rJC799L2Q/maxresdefault.jpg"
]

const mockImages = mockUrls.map((url, index) => ({
  id: index +1,
  url
}));

export default function HomePage() {
  return (
    <main className="">
      <div className="flex flex-wrap gap-4">{
        [...mockImages, ...mockImages, ...mockImages].map((image) => (
          <div key={image.id} className="w-1/2 p-4">
            <img src={image.url} alt="image" />
          </div>
        ))
      }</div>
    </main>
  );
}
